apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1 # Number of instances (pods) to run
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: myacr.azurecr.io/chrisus_image # Your Docker image in Azure Container Registry
          ports:
            - containerPort: 80
